ci: include db migration

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,6 +17,25 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v4
 
+      - name: Check for credentials in diff
+        run: |
+          git diff --cached | grep -E 'DATABASE_URL'
+          if [ $? -eq 0 ]; then
+            echo "::warning title=Potential Credentials Detected::Review the diff for potential credentials!"
+            exit 0 #soft fail.
+          fi
+
+      - name: Check for credentials in diff HEAD
+        run: |
+          git diff HEAD | grep -E 'DATABASE_URL'
+          if [ $? -eq 0 ]; then
+            echo "::warning title=Potential Credentials Detected::Review the diff for potential credentials!"
+            exit 0 #soft fail
+          fi
+
+      - name: Set up goose
+        run: go install github.com/pressly/goose/v3/cmd/goose@latest && goose -version
+
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
@@ -38,6 +57,9 @@ jobs:
 
       - name: 'Build and push to Google Artifact Registry'
         run: 'gcloud builds submit --tag us-central1-docker.pkg.dev/lithe-cocoa-458909-v2/notely-ar-repo/notely:latest .'
+
+      - name: 'Database migration'
+        run: './scripts/migrateup.sh'
 
       - name: Deploy to Cloud Run
         run: gcloud run deploy notely --image us-central1-docker.pkg.dev/lithe-cocoa-458909-v2/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project lithe-cocoa-458909-v2 --max-instances=4
